In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('titanic.csv')
# df.head()

In [3]:
inputs = df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked','Survived'], axis='columns')
inputs.head()

   Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [4]:
target = df.Survived
# target.head()

In [5]:
# np.where(pd.isnull(inputs))
# np.where(pd.isna(inputs))

In [6]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [7]:
inputs['Age'] = inputs['Age'].fillna(inputs['Age'].mean())

In [8]:
inputs.columns[inputs.isna().any()]

Index([], dtype='object')

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [10]:
# inputs_le = inputs
inputs.Sex = le.fit_transform(inputs.Sex)
inputs.head()

   Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    0  38.0  71.2833
2       3    0  26.0   7.9250
3       1    0  35.0  53.1000
4       3    1  35.0   8.0500

In [11]:
X = inputs[['Pclass','Sex','Age','Fare']].values
# X.shape

In [12]:
y = target.values
# y.shape

In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [14]:
ct_ohe = ColumnTransformer([('Sex',OneHotEncoder(),[1])],remainder='passthrough')
ct_ohe

ColumnTransformer(remainder='passthrough',
                  transformers=[('Sex', OneHotEncoder(), [1])])

In [15]:
X = ct_ohe.fit_transform(X)
X

array([[ 0.        ,  1.        ,  3.        , 22.        ,  7.25      ],
       [ 1.        ,  0.        ,  1.        , 38.        , 71.2833    ],
       [ 1.        ,  0.        ,  3.        , 26.        ,  7.925     ],
       ...,
       [ 1.        ,  0.        ,  3.        , 29.69911765, 23.45      ],
       [ 0.        ,  1.        ,  1.        , 26.        , 30.        ],
       [ 0.        ,  1.        ,  3.        , 32.        ,  7.75      ]])

In [16]:
X = X[:,1:]
X

array([[ 1.        ,  3.        , 22.        ,  7.25      ],
       [ 0.        ,  1.        , 38.        , 71.2833    ],
       [ 0.        ,  3.        , 26.        ,  7.925     ],
       ...,
       [ 0.        ,  3.        , 29.69911765, 23.45      ],
       [ 1.        ,  1.        , 26.        , 30.        ],
       [ 1.        ,  3.        , 32.        ,  7.75      ]])

In [17]:
# inputs = X

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [19]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [20]:
model.fit(X_test, y_test)

GaussianNB()

In [21]:
model.score(X_test, y_test)

0.8022388059701493

In [22]:
X_test[0:10]

array([[  0.        ,   3.        ,  29.69911765,   7.7875    ],
       [  1.        ,   2.        ,  30.        ,  13.        ],
       [  1.        ,   2.        ,  34.        ,  13.        ],
       [  1.        ,   1.        ,  51.        ,  26.55      ],
       [  1.        ,   3.        ,  17.        ,   8.6625    ],
       [  1.        ,   2.        ,  30.        ,  13.        ],
       [  0.        ,   2.        ,  30.        ,  12.35      ],
       [  1.        ,   1.        ,  29.69911765,  35.5       ],
       [  1.        ,   1.        ,  46.        ,  79.2       ],
       [  0.        ,   1.        ,  14.        , 120.        ]])

In [23]:
y_test[0:10]

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 1], dtype=int64)

In [24]:
model.predict(X_test[0:10])

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 1], dtype=int64)

In [25]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(), X_train, y_train, cv=5)

array([0.736     , 0.816     , 0.784     , 0.77419355, 0.80645161])