In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('homeprices.csv')
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [3]:
model = LinearRegression()
# model.fit(df[['town','area']], df.price)
model.fit(df[['area']], df.price)
# model.score()
# model.score(df[['town','area']], df.price)
model.score(df[['area']], df.price)

0.8683414156126124

In [4]:
model.predict(df[['area']])

array([564623.52209085, 611941.50591164, 635600.49782203, 682918.48164281,
       730236.4654636 , 564623.52209085, 588282.51400124, 647429.99377722,
       682918.48164281, 564623.52209085, 600112.00995644, 623771.00186683,
       682918.48164281])

# Creating dummy variables using pandas dataframe

In [5]:
dummies = pd.get_dummies(df.town)
dummies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [6]:
merged = pd.concat([df, dummies])
merged

,town,area,price,monroe township,robinsville,west windsor
0,monroe township,2600.0,550000.0,NaN,NaN,NaN
1,monroe township,3000.0,565000.0,NaN,NaN,NaN
2,monroe township,3200.0,610000.0,NaN,NaN,NaN
3,monroe township,3600.0,680000.0,NaN,NaN,NaN
4,monroe township,4000.0,725000.0,NaN,NaN,NaN
5,west windsor,2600.0,585000.0,NaN,NaN,NaN
6,west windsor,2800.0,615000.0,NaN,NaN,NaN
7,west windsor,3300.0,650000.0,NaN,NaN,NaN
8,west windsor,3600.0,710000.0,NaN,NaN,NaN
9,robinsville,2600.0,575000.0,NaN,NaN,NaN
10,robinsville,2900.0,600000.0,NaN,NaN,NaN
11,robinsville,3100.0,620000.0,NaN,NaN,NaN
12,robinsville,3600.0,695000.0,NaN,NaN,NaN
0,NaN,NaN,NaN,1.0,0.0,0.0
1,NaN,NaN,NaN,1.0,0.0,0.0
2,NaN,NaN,NaN,1.0,0.0,0.0
3,NaN,NaN,NaN,1.0,0.0,0.0
4,NaN,NaN,NaN,1.0,0.0,0.0
5,NaN,NaN,NaN,0.0,0.0,1.0
6,NaN,NaN,NaN,0.0,0.0,1.0
7,NaN,NaN,NaN,0.0,0.0,1.0
8,NaN,NaN,NaN,0.0,0.0,1.0
9,NaN,NaN,NaN,0.0,1.0,0.0
10,NaN,NaN,NaN,0.0,1.0,0.0
11,NaN,NaN,NaN,0.0,1.0,0.0
12,NaN,NaN,NaN,0.0,1.0,0.0

In [7]:
merged = pd.concat([df, dummies], axis='columns')
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [8]:
# final = merged.drop(merged.town, merged['west windsor'])
# final = merged.drop(merged.town, axis='columns')
# final = merged.drop(merged['west windsor'], axis='columns')
final = merged.drop(['town','west windsor'], axis='columns')
final

    area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [9]:
# X = merged.drop(['town','west windsor', 'price'], axis='columns')
X = final.drop(['price'], axis='columns')
X

    area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [10]:
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [11]:
# new_model = LinearRegression()
new_model = model
new_model.fit(X, y)
new_model.score(X, y)

0.9573929037221871

In [12]:
new_model.predict(X)

array([539709.7398409 , 590468.71640508, 615848.20468716, 666607.18125134,
       717366.15781551, 579723.71533005, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.15136531, 603465.38378844, 628844.87207052,
       692293.59277574])

In [13]:
# 3400 sqr ft home in west windsor i.e. [3400,0,0].
# It's mean west windsor is 1 (monroe township, robinsville, west windsor).
new_model.predict([[3400, 0, 0]])

C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.66845839])

In [14]:
# 2800 sqr ft home in robbinsville i.e. [2800,0,1]
# It's mean robbinsville is 1 (monroe township, robinsville, west windsor).
new_model.predict([[2800, 0, 1]])

C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

# sklearn onehotencoding

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [16]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [17]:
X = dfle[['town', 'area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [18]:
y = dfle.price.values
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000], dtype=int64)

# Now use one hot encoder to create dummy variables for each of the town

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [20]:
# ct_ohe = ColumnTransformer([('town', OneHotEncoder, [0])], remainder='passthrough')
ct_ohe = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder='passthrough')
X = ct_ohe.fit_transform(X)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [21]:
# drop a column "monroe township" to avoid dummy variable trap
X = X[:, 1:] # all rows included but in column, inclusion begins from the 1st and then include all columns
# Slicing [0th row : till nth row, 0th column : till nth column]
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [22]:
# ohe_model = LinearRegression()
ohe_model = model
ohe_model.fit(X, y)
ohe_model.score(X, y)

0.9573929037221873

In [23]:
ohe_model.predict(X)

array([539709.7398409 , 590468.71640508, 615848.20468716, 666607.18125134,
       717366.15781552, 579723.71533004, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.1513653 , 603465.38378843, 628844.87207052,
       692293.59277574])

In [24]:
# 3400 sqr ft home in "west windsor" i.e. [0,1,3400]. 
# [monroe township, robinsville, west windsor]
ohe_model.predict([[0, 1, 3400]])

array([681241.66845839])

In [25]:
# [monroe township, robinsville, west windsor]
# 2800 sqr ft home in robbinsville [1,0,2800]
ohe_model.predict([[1, 0, 2800]])

array([590775.63964739])